CREATE TABLE R(
    A INTEGER,
    B INTEGER,
    PRIMARY KEY (A, B)
);

CREATE TABLE S(
    C INTEGER,
    D INTEGER,
    PRIMARY KEY (C, D)
);

INSERT INTO R (A, B) VALUES
(4, 6),
(4, 7),
(3, 4),
(3, 5);

INSERT INTO S (C, D) VALUES
(4, 6),
(4, 7),
(3, 8),
(4, 5);

SELECT * FROM R;
SELECT * FROM S;
SELECT DISTINCT A
FROM R, S
WHERE R.A = S.C AND R.B = S.D;
SELECT DISTINCT A
FROM R JOIN S ON R.A = S.C AND R.B = S.D;
SELECT *
FROM R LEFT OUTER JOIN S ON R.A = S.C AND R.B = S.D;
DROP TABLE R;
DROP TABLE S;